### ISSUE TITLE
Adding aiida-fleur maintainers to feedstock

### ISSUE THREAD

**Issue by janssenhenning** [conda-forge/aiida-fleur-feedstock#6]
### Comment:

Hey @chrisjsewell I noticed that you uploaded `aiida-fleur` to conda-forge. Thanks for this effort.
I think it would be good if atleast one `aiida-fleur` maintainer is also added as a maintainer of this feedstock
I would volunteer for this. I am already a maintainer for these closely connected feedstocks
- Main FLEUR code https://github.com/conda-forge/fleur-feedstock
- IO/utils package for aiida-fleur https://github.com/conda-forge/masci-tools-feedstock

**Comment by chrisjsewell** [comment]
Hey @janssenhenning 👋 
Yep as you may have noticed, I'm basically trying to get the whole of aiida-common-workflows on to conda-forge 😅 (https://anaconda.org/search?q=aiida), with the goal to use this also within https://github.com/marvel-nccr/quantum-mobile

I was just wanted to get all these recipes into conda-forge first, and make sure they all work together, then indeed I was going to message all you guys maintaining the packages, to explain it and chat about adding maintainers 👍

**Comment by chrisjsewell** [comment]
The key thing for me, above the PyPI release, is to have this dependency constraint with the actual simulation code, so that e.g. here we are saying that `aiida-fleur=1.3.1` is compatible with `fleur>=1,<7`
